JdJobsDashBoard/Controllers/GoogleReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.OleDb;
using System.Data.OracleClient;
using System.Configuration;
using System.Text.RegularExpressions;
using JdJobsDashBoard.Models;
using System.Security.Principal;
using System.Runtime.InteropServices;
using DocumentFormat.OpenXml.Drawing;
using System.IO;
using System.Net;
using System.Text;
using System.Collections.ObjectModel;
using System.Management.Automation;
using System.Security;
using System.Diagnostics;

namespace JdJobsDashBoard.Controllers
{
    public class GoogleReportsController : Controller
    {
        LibraryContext objContext = new LibraryContext();
        // GET: GoogleReports
        public ActionResult Index()

        {

            List<Sites> publishers = objContext.getSites.ToList();
            ViewBag.Sites = publishers;

            //string process = "";
            bool Isprocess = false;
            var proc = System.Diagnostics.Process.GetProcesses().ToArray();

            foreach (var item in proc)
            {
                if (item.ProcessName == "JD.FeedManager.GoogleAnalytics.SqlLoaderRunner" || item.ProcessName == "JD.FeedManager.GoogleAnalytics")
                    //process += "'" + item.ProcessName + "'" + " , ";
                    Isprocess = true;
            }
            ViewBag.process = Isprocess;
            var items = GetGaData();//GetGaData();
            if (items != null && items.Count > 0)
            {
                ViewBag.GaItems = items;
                return View(ViewBag);
            }
            else
                return View();

        }

        private string IsProcessRunning(string sProcessName)
        {
            System.Diagnostics.Process[] proc = System.Diagnostics.Process.GetProcessesByName(sProcessName);
            if (proc.Length > 0)
            {
                return String.Format("{0}is  running!", sProcessName);
            }
            else
            {
                return String.Format("{0}is not running!", sProcessName);
                // start your process
            }
        }

        static private string GetConnectionString()
        {
            // To avoid storing the connection string in your code, 
            // you can retrieve it from a configuration file. 
            return ConfigurationManager.AppSettings["GABIPRDConnection"];
        }

        static private string GetQuery()
        {
            string strDate = DateTime.Now.AddDays(-1).ToString("dd-MMM-yyyy");

            string strQuery = @"SELECT
                                'Topline' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE,
                                count (t.profileid) as rowcount
                                from
                                GOOGAN.TOPLINE T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'PrimaryDetails' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.PRIMARYDETAILS T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'LCPrimaryDetails' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.LOCALCURRENCY_PRIMARYDETAILS T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'Primaryextended' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONSREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.Primaryextended T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                Union all

                                SELECT
                                'FULLFUNNEL' AS TABLE_NAME
                                ,0 AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.FULLFUNNEL T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                Union all

                                SELECT
                                'FUNNELBYHOUR' AS TABLE_NAME
                                ,0 AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.FUNNELBYHOUR T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'


                                Union all

                                SELECT
                                'EXPERIMENTS' AS TABLE_NAME
                                ,0 AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.EXPERIMENTS T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                Union all

                                SELECT
                                'EVENTERRORS' AS TABLE_NAME
                                ,0 AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.EVENTERRORS T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                REPORTDAY = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'ToplineByDevice' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.TOPLINEBYDEVICE T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'OrderID_LookUp' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.OrderID_LookUp T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'TechnicalDetails' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.TechnicalDetails T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

                                UNION ALL

                                SELECT
                                'LandingPagePerformance' AS TABLE_NAME
                                ,SUM(T.TRANSACTIONREVENUE) AS TRANS_REVENUE
                                ,count (t.profileid) as rowcount
                                FROM
                                GOOGAN.LandingPagePerformance T
                                INNER JOIN GOOGAN.PROFILEID_LOOKUP P ON T.PROFILEID = P.PROFILEID
                                where
                                APPLICABLEDATE = trunc(sysdate)-1
                                AND P.SITE = 'JD'

JdJobsDashBoard/Views/GoogleReports/Index.cshtml
@*@model JdJobsDashBoard.Models.Sites*@
@{
    ViewBag.Title = "Google DashBoard";
}
<style>
    td,th{
        padding:3px;
    }
</style>
<h2>Google Analytics</h2>
<div style="margin-top:40px;display:none" id="divmsg">
    <p style="color:orangered;font-weight: bold">* Currently Jobs are running.</p>
</div>


<table border="1" id="tbl_Report">
    <tr>
        <th>
            Table_Name
        </th>
        <th>
            Trans_Revenue
        </th>
        <th>
            Row_Count
        </th>
        <th>Re-run <input type="checkbox" id="checkAll" style="margin-left: 22px;"></th>
        <th>Dedupe <input type="checkbox" id="checkAll_dedupe" style="margin-left: 22px;"></th>
    </tr>
    @foreach (var item in ViewBag.GaItems)
    {
        <tr>
            <td>
                @item.tableName
            </td>
            <td>
                @item.transRevenue
            </td>
            <td>
                @item.RowCount
            </td>
            <td align="center" style="width:60px">
                <input type="checkbox" name='@item.tableName' id="chk" value='@item.tableName' class="g1"/>
            </td>
            <td align="center" style="width:60px">
                <input type="checkbox" name='@item.tableName' id="chk_dedupe" value='@item.tableName' class="g2"/>
            </td>
        </tr>
    }
</table>
<div style="margin-top: 5px;margin-left: 399px;">
    <input type="button" name="name" value="Re-Run" id="btnrerun" onclick="Rerun()" />
    <input type="button" name="name" value="Dedupe" id="btndedupe" onclick="Dedupe()" />
</div>
<div style="margin-top:40px">
    <p style="color:orangered;font-weight: bold">* Note: Don't reload the browser while processing. Wait until you see Files are downloaded successfully.</p>
</div>

<div class="bs-example">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Site Specific Re-run</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    <label class="add-fields" id="lblFascia">Fascia</label>
                    <span id="dvFascias" class="mlft">
                        @Html.DropDownList("Name", new SelectList(ViewBag.Sites, "Id", "Name"), "Please select site", new { @id = "ddlSites" })
                        <input type="button" name="name" value="Site Specific Re-run" id="btnrerun" onclick="SiteRerun()" />
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    //$(document).ready(function () {
    //    //setInterval(function () {
    //    //    GetCountfiles();
    //    //}, 10 * 1000);
    //});

    //function GetCountfiles() {
    //    $.ajax({
    //        type: "GET",
    //        url: "/GoogleReports/GetCountfiles",
    //        dataType: "json",
    //        success: function (data) {
    //            //alert('Number of files : ' + data);
    //            debugger;
    //            if (data < 1) {
    //                $('#chk').attr("disabled", false);
    //                $("#chk").prop("checked", false);
    //            }
    //            else {
    //                $('#chk').attr("disabled", true);
    //            }
    //        },
    //        error: function () {
    //            alert("Error occured!!")
    //        }
    //    });
    //}
    $(document).ready(function () {
        var process='@Html.Raw(@ViewBag.process)';
        if (process == 'True') {
            $('input#chk').attr("disabled", true);
            $('input#chk_dedupe').attr("disabled", true);
            $('input#checkAll').attr("disabled", true);
            $('input#checkAll_dedupe').attr("disabled", true);
            $('input#btnrerun').attr("disabled", true);
            $('input#btndedupe').attr("disabled", true);
            $('#divmsg').css("display", "block");
        }
    });
    $("#checkAll").click(function () {
        if ($("#checkAll").is(':checked')) {
            $("input[type=checkbox]#chk").each(function () {
                $(this).prop("checked", true);
                $("input[type=checkbox]#chk_dedupe").prop("checked", false);
                $("input[type=checkbox]#checkAll_dedupe").prop("checked", false);
            });
        } else {
            $("input[type=checkbox]#chk").each(function () {
                $(this).prop("checked", false);
                $("input[type=checkbox]#chk_dedupe").prop("checked", false);
                $("input[type=checkbox]#checkAll_dedupe").prop("checked", false);
            });
        }
    });

    $("#checkAll_dedupe").click(function () {
        if ($("#checkAll_dedupe").is(':checked')) {
            $("input[type=checkbox]#chk_dedupe").each(function () {
                $(this).prop("checked", true);
                $("input[type=checkbox]#chk").prop("checked", false);
                $("input[type=checkbox]#checkAll").prop("checked", false);
            });
        } else {
            $("input[type=checkbox]#chk_dedupe").each(function () {
                $(this).prop("checked", false);
                $("input[type=checkbox]#chk").prop("checked", false);
                $("input[type=checkbox]#checkAll").prop("checked", false);
            });
        }
    });

    var newUrl = '@Url.Action("Index", "GoogleReports")';
    // Re-run GA
    function Rerun() {
        var favorite = [];
        $.each($("input[id='chk']:checked"), function () {
            favorite.push($(this).val());
        });

        if (favorite.length === 0) {
            alert('Please select checkbox for Re-run Google Analytics');
            return;
        }

        $('input#chk').attr("disabled", true);
        $('input#chk_dedupe').attr("disabled", true);
        $('input#checkAll').attr("disabled", true);
        $('input#checkAll_dedupe').attr("disabled", true);
        $('input#btnrerun').attr("disabled", true);
        $('input#btndedupe').attr("disabled", true);

        $.ajax({
            url: '@Url.Action("RunPS1File", "GoogleReports")',
            type: "POST",
            data: { tableName: favorite },
            dataType: 'json',
            success: function (result) {
                alert(result);
                window.location.href = newUrl;
                $('input#chk').attr("disabled", false);
                $('input#chk_dedupe').attr("disabled", false);
                $('input#checkAll').attr("disabled", false);
                $('input#checkAll_dedupe').attr("disabled", false);
                $('input#btnrerun').attr("disabled", false);
                $('input#btndedupe').attr("disabled", false);

            },
            error: function (request, status, error) {
                alert(request.responseText);
            }
        });
    }

    // Re-run GA
    function SiteRerun() {
        if ($('#ddlSites').val() == "") {
            alert("Please select proper country in given dropdown.")
            return;
        }
        var favorite = [];
        $.each($("input[id='chk']:checked"), function () {
            favorite.push($(this).val());
        });

        if (favorite.length === 0) {
            alert('Please select checkbox for Re-run Google Analytics');
            return;
        }

        $('input#chk').attr("disabled", true);
        $('input#chk_dedupe').attr("disabled", true);
        $('input#checkAll').attr("disabled", true);
        $('input#checkAll_dedupe').attr("disabled", true);
        $('input#btnrerun').attr("disabled", true);
        $('input#btndedupe').attr("disabled", true);

        $.ajax({
            url: '@Url.Action("RunPS1FileSite", "GoogleReports")',
            type: "POST",
            data: { tableName: favorite, selectedSite: $('#ddlSites').val() },
            dataType: 'json',
            success: function (result) {
                alert(result);
                window.location.href = newUrl;
                $('input#chk').attr("disabled", false);
                $('input#chk_dedupe').attr("disabled", false);
                $('input#checkAll').attr("disabled", false);
                $('input#checkAll_dedupe').attr("disabled", false);
                $('input#btnrerun').attr("disabled", false);
                $('input#btndedupe').attr("disabled", false);

            },
            error: function (request, status, error) {
                alert(request.responseText);
            }
        });
    }

    //Dedupe
    function Dedupe() {
       
        var arrDedupe = [];
        $.each($("input[id='chk_dedupe']:checked"), function () {
            arrDedupe.push($(this).val());
        });

        if (arrDedupe.length === 0) {
            alert('Please select checkbox for Dedupe table');
            return;
        }

        $('input#chk_dedupe').attr("disabled", true);
        $('input#chk').attr("disabled", true);
        $('input#checkAll').attr("disabled", true);
        $('input#checkAll_dedupe').attr("disabled", true);
        $('input#btnrerun').attr("disabled", true);
        $('input#btndedupe').attr("disabled", true);
        $.ajax({
            url: '@Url.Action("DedupeNightlyReport", "GoogleReports")',
            type: "POST",
            data: { tableName: arrDedupe },
            dataType: 'json',
            success: function (result) {
                alert(result);
                window.location.href = newUrl;
                $('input#chk_dedupe').attr("disabled", false);
                $('input#chk_dedupe').attr("disabled", true);
                $('input#checkAll').attr("disabled", false);
                $('input#checkAll_dedupe').attr("disabled", false);
                $('input#btnrerun').attr("disabled", false);
                $('input#btndedupe').attr("disabled", false);

            },
            error: function (request, status, error) {
                alert(request.responseText);
            }
        });
    }

    $('.g1').on('change', function () {
        $('.g2').not(this).prop('checked', false);
    });
    $('.g2').on('change', function () {
        $('.g1').not(this).prop('checked', false);
    });
</script>

<style type="text/css">
    .bs-example {
        /*margin: 20px;*/
    }
</style>